### ISSUE TITLE
strange load

### ISSUE THREAD

**Issue by microwin7** [TheTadeSK/QuickBoard#6]
![image](https://user-images.githubusercontent.com/12544425/83918722-fd450480-a781-11ea-9a14-0fb7635ece56.png)
```
title:
- '&f&l鐃 &e&lHUNGER GAMES &f&l陚&r'
text:
  - '&7%localtime_time_dd/MM/YY%'
  - ''
  - '&6Ваша статистика:&r'
  - '&eУбийств&r&4 ➟ &f%statistic_player_kills%'
  - '&eCмертей&r&4 ➟ &f%statistic_deaths%'
  - '&eКиллПоинтов&r&4 &4➟ &f%playerpoints_points%'
  - '&f'
  - '&6Информация о Вас:&r'
  - '&2Аккаунт: &f%SemperChat_color%%player_name%'
  #- '&2Рубли: &f%SemperAnteAPI_realmoney% ₽'
  #- '&2Баланс: &f%vault_eco_balance% $'
  - '&2Пинг: &f%player_ping%ms'
  - ''
  - '&6gamai.ru'
updater:
  title: -1
  text: 60
enabledWorlds:
- world
- Lobby
changeableText:
scroller:
```
